### ISSUE TITLE
ghost artifacts

### ISSUE THREAD

**Issue by TumeniNodes** [TumeniNodes/blender_bumbles#1]
Any help in resolving the issues with this model in-game would be greatly appreciated.
I have searched for ways to possibly solve it, but nothing has been of any use.

![screenshot_20190703_234221](https://user-images.githubusercontent.com/18484258/60748531-ee941300-9f5c-11e9-9ea0-8d84683aa613.jpg)

![screenshot_20190704_105351](https://user-images.githubusercontent.com/18484258/60748534-f3f15d80-9f5c-11e9-9f0a-5cc39d5c57f8.jpg)

No methods I have found have been able to detect these artifacts within Blender itself. In Blender, they look like clean models... with no duplicated vertices, etc.
So I have no idea what is going on. The only thing I do know, is they were created during the cutting, and also shaping of the top of the arched door, even though I did it using steps I found in a few tutorials, step by step...

**Comment by VanessaE** [comment]
image we discussed in IRC:  ![image](https://user-images.githubusercontent.com/1733537/60749086-0a9ab300-9f63-11e9-9866-7d6dacc7a25e.png)

**Comment by VanessaE** [comment]
[arch_door_L.obj.zip](https://github.com/TumeniNodes/blender_bumbles/files/3364250/arch_door_L.obj.zip)

**Comment by TumeniNodes** [comment]
On a side note,I may use a similar method with the textures for MTG doors too... to fix some of their blurriness.
The moment you add the extra bits for UV mapping, it blurs the image on rendering outside of Blender, though I guess there is a method in regards to scaling which can be used too but, keeping the texture in relation to the dimensions of the model is key to having nice crisp textures when rendering in, say MTG

**Comment by VanessaE** [comment]
Ok ignore those files.  try these:
![arch_doors_wood](https://user-images.githubusercontent.com/1733537/60749920-1c825300-9f6f-11e9-9b40-22050041fac7.png)
[arch_door_L.obj.zip](https://github.com/TumeniNodes/blender_bumbles/files/3364294/arch_door_L.obj.zip)
[arch_door_R.obj.zip](https://github.com/TumeniNodes/blender_bumbles/files/3364296/arch_door_R.obj.zip)
[arch_door_L_revised_by_VE.blend.zip](https://github.com/TumeniNodes/blender_bumbles/files/3364295/arch_door_L_revised_by_VE.blend.zip)

**Comment by TumeniNodes** [comment]
These look great thank you! the artifacts are reversed now, thus to not impact the top cuts
![screenshot_20190705_215851](https://user-images.githubusercontent.com/18484258/60750003-5738bb00-9f70-11e9-99d5-458583d9a05e.jpg)
![screenshot_20190705_215912](https://user-images.githubusercontent.com/18484258/60750007-59027e80-9f70-11e9-9a47-2beca2711b70.jpg)

**Comment by TumeniNodes** [comment]
Thank you my dear... I can close this now
This was a big hurdle for me to move forward with this mod.
